DROP TABLE FILEBOARD;
DROP SEQUENCE FILEBOARD_SEQ;
CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE FILEBOARD(
    FID NUMBER(6) PRIMARY KEY,
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    FTITLE VARCHAR2(100) NOT NULL,
    FCONTENT VARCHAR2(1000),
    FFILENAME VARCHAR2(30),
    FRDATE    DATE DEFAULT SYSDATE,
    FHIT      NUMBER(6) DEFAULT 0,
    FGROUP   NUMBER(6) NOT NULL,
    FSTEP    NUMBER(3) NOT NULL,
    FINDENT  NUMBER(3) NOT NULL);

-- 더미데이터(원글)
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME,  
        FGROUP, FSTEP, FINDENT)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa','title','content',null, 
        FILEBOARD_SEQ.CURRVAL, 0, 0);
SELECT * FROM FILEBOARD;
-- 더미데이터(위의 1번글에 대한 첫번째 답변글)
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME,
        FGROUP, FSTEP, FINDENT)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa','reply','content', null,
        1, 1, 1);
select * from fileboard order by fgroup desc, fstep;
-- 더미데이터 (위의 1번글에 대한 두번째 답변글)
--    답변글 추가전 STEP a 수행
UPDATE FILEBOARD SET FSTEP = FSTEP+1 
    WHERE FGROUP = 1 AND FSTEP>0;
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME,
        FGROUP, FSTEP, FINDENT)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa','reply','content', null,
        1, 1, 1);
COMMIT;
-- 글목록(startRow부터 endRow까지) - 글번호, 작성자이름, ...
SELECT F.*, MNAME FROM FILEBOARD F, MEMBER M WHERE F.MID=M.MID 
                ORDER BY FGROUP DESC, FSTEP; -- 출력 기준
SELECT * FROM 
    (SELECT ROWNUM RN, A.* FROM 
    (SELECT F.*, MNAME FROM FILEBOARD F, MEMBER M WHERE F.MID=M.MID 
                ORDER BY FGROUP DESC, FSTEP) A)
    WHERE RN BETWEEN 1 AND 11;
-- 글갯수
SELECT COUNT(*) FROM FILEBOARD;
-- 글쓰기(원글)
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, fFILENAME,  
        FGROUP, FSTEP, FINDENT)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa','title','content',null, 
        FILEBOARD_SEQ.CURRVAL, 0, 0);
-- FHit 하나 올리기(1번글 조회수 하나 올리기)
UPDATE FILEBOARD SET FHIT = FHIT +1 WHERE FID=1;
-- bId로 글 dto보기
SELECT F.*, MNAME FROM FILEBOARD F, MEMBER M WHERE M.MID=F.MID AND FID=1;
-- 글 수정하기(FId, FTitle, FContent, FILENAME,  FIp, FDATE)
UPDATE FILEBOARD SET FTITLE = '제목',
                    FCONTENT = '본문',
                    fFILENAME = NULL,
                    FDATE = SYSDATE
            WHERE FID = 1;
-- 글 삭제하기(bId로 삭제하기)
DELETE FROM FILEBOARD WHERE FID=3;
--    답변글 추가전 STEP a 수행
UPDATE FILEBOARD SET FSTEP = FSTEP+1 
    WHERE FGROUP = 1 AND FSTEP>0;
-- 답변글 쓰기
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, fFILENAME,
        FGROUP, FSTEP, FINDENT)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'bbb','reply','content', null,
        1, 1, 1);
commit;
