DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    MID      VARCHAR2(30) PRIMARY KEY, --이름
    MPW      VARCHAR2(30) NOT NULL,  
    MNAME    VARCHAR2(30) NOT NULL,
    MADDRESS VARCHAR2(255),
    MTEL     VARCHAR2(30) NOT NULL,
    MEMAIL   VARCHAR2(30) NOT NULL,
    MBIRTH   DATE,
    MRDATE   DATE DEFAULT SYSDATE
);
-- mId 중복체크
SELECT * FROM MEMBER WHERE MID='aaa';
-- 회원가입
INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL,MBIRTH)
        VALUES ('aaa','111','지단','프랑스','010-0000-0000','hong@naver.com','1990/12/12');

INSERT INTO MEMBER (MID,MPW,MNAME,MADDRESS,MTEL,MEMAIL,MBIRTH)
        VALUES ('bbb','111','카카','브라질','010-0000-0000','hong@naver.com','1990/12/12');
-- 로그인 (mID, mPW)
SELECT * FROM MEMBER WHERE MID='aaa' AND MPW='111';
--세션에 넣기 위해 mId로 member dto가져오기
SELECT * FROM MEMBER WHERE MID='www';
--회원정보수정 (MPW, MADDRESS, MTEL, MEMAIL / MID)
UPDATE MEMBER SET MPW='222', MADDRESS='잉글랜드', MTEL='010-1111-1111', MEMAIL='hong@naver.com' 
    WHERE MID='bbb';

-- 회원목록(startRow ~ endRow)
SELECT * FROM MEMBER ORDER BY MRDATE DESC , MNAME DESC;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM
        (SELECT * FROM MEMBER ORDER BY MRDATE DESC )A)
        WHERE RN BETWEEN 1 AND 10;


-- 가입한 전체 회원 명수
SELECT COUNT(*) FROM MEMBER;
-- 회원 삭제
DELETE FROM MEMBER WHERE MID='www';

COMMIT;










