DROP TABLE PRODUCT;
DROP SEQUENCE PRODUCT_SEQ;
CREATE TABLE PRODUCT(
    PCODE VARCHAR2(30) PRIMARY KEY,
    PNAME VARCHAR2(30) NOT NULL,
    PDES VARCHAR2(1000),
    PTYPE VARCHAR2(30) NOT NULL,
    PFILENAME VARCHAR2(100) NOT NULL,
    PPRICE NUMBER(9) NOT NULL,
    PSTOCK NUMBER(9) NOT NULL,
    PRDATE DATE DEFAULT SYSDATE    
);
SELECT * FROM PRODUCT;


-- 상품등록
INSERT INTO PRODUCT (PCODE,PNAME,PDES,PTYPE,PFILENAME,PPRICE,PSTOCK) VALUES ('001','000','','apl','#', 3600, 10000); 
-- 상품 목록 최근순 

SELECT * FROM PRODUCT WHERE PTYPE='' ORDER BY PRDATE DESC; 
SELECT * FROM (SELECT ROWNUM RN, A.* FROM
    (SELECT * FROM PRODUCT WHERE PTYPE='' ORDER BY PRDATE DESC)A) WHERE RN BETWEEN 2 AND 3;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM
    (SELECT * FROM PRODUCT ORDER BY PRDATE DESC)A) WHERE RN BETWEEN 1 AND 10;
-- 전체 상품 개수
SELECT COUNT(*) FROM PRODUCT;

-- 타입별 상품 개수

SELECT COUNT(*) FROM PRODUCT WHERE PTYPE='apl';
-- PCODE 로 가져오기 
SELECT * FROM PRODUCT WHERE PCODE='001';

-- 상품 수정
UPDATE PRODUCT SET PNAME='000', PTYPE='apl',PFILENAME='#',PPRICE='3000',PSTOCK='20' WHERE PCODE='001';

-- 상품 삭제 

DELETE FROM PRODUCT WHERE PCODE='001';

-- 주문시 재고수량 변경
UPDATE PRODUCT SET PSTOCK=PSTOCK-10 WHERE PCODE='001';




COMMIT;



