DROP TABLE QNA;
CREATE TABLE QNA(
    QNO NUMBER(10) PRIMARY KEY,
    AID VARCHAR2(10) REFERENCES ADMIN(AID),
    MID VARCHAR2(30) REFERENCES MEMBER(MID),
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(2000),
    QFILENAME VARCHAR2(100),
    QGROUP NUMBER(10),
    QSTEP NUMBER(10),
    QINDENT NUMBER(10),
    QHIT NUMBER(10),
    QRDATE DATE );
    
    
DROP SEQUENCE QNA_SEQ;
CREATE SEQUENCE QNA_SEQ MAXVALUE 999 NOCACHE NOCYCLE;

SELECT * FROM QNA;
SELECT * FROM MEMBER;
INSERT INTO QNA (QNO, AID, MID, QTITLE ,QCONTENT, QFILENAME, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'bbb', null, '제목','내용', null, QNA_SEQ.CURRVAL, 0, 0 );

INSERT INTO QNA (QNO, AID, MID, QTITLE ,QCONTENT, QFILENAME, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'admin', null, '제목', '내용', null, QNA_SEQ.CURRVAL, 0, 0 );
    
    INSERT INTO QNA (QNO, AID, MID, QTITLE, QCONTENT, QFILENAME, QGROUP, QSTEP, QINDENT)
VALUES (QNA_SEQ.NEXTVAL,  'TEST_AID' ,'TEST_MID', 'TEST_TITLE' ,'TEST_CONTENT','TEST_FILENAME' , QNA_SEQ.CURRVAL, 0, 0 );
    
    commit;
-- 글목록

SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, 
   QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
   FROM QNA ORDER BY QGROUP DESC, QSTEP;
   
SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
    (SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M 
        WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M 
        WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, MID, AID, 
        QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
        WHERE RN BETWEEN 1 AND 10;

-- 글 개수 

SELECT COUNT(*) FROM QNA;

-- 글 쓰기(원글) 
INSERT INTO QNA (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'aaa123', null, '제목', '내용', null, null, QNA_SEQ.CURRVAL, 0, 0 );
    
-- 글 조회수 올리기
UPDATE QNA SET QHIT = QHIT+1 WHERE QNO='1';

-- 글 수정하기

UPDATE QNA SET QTITLE='바뀐제목', QCONTENT='바뀐내용', QFILENAME1=null, QFILENAME2=null, QRDATE=SYSDATE
    WHERE QNO='1';

-- QNO 로 DTO 보기 (상세보기)
SELECT QNO, (SELECT MNAME FROM QNA Q, MEMBER M WHERE Q.MID=M.MID AND QNA.QNO=QNO) ||
    (SELECT ANAME FROM QNA Q, ADMIN M WHERE Q.AID=M.AID AND QNA.QNO=QNO) WRITER, MID, AID,
   QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT, QHIT, QRDATE
   FROM QNA WHERE QNO='3';
   


-- 답변글 수행전 STEP A 수행 

UPDATE QNA SET QSTEP = QSTEP+1 WHERE QGROUP=4 AND QSTEP>0;

-- 답변글 쓰기
INSERT INTO QNA 
    (QNO, MID, AID, QTITLE, QCONTENT, QFILENAME1, QFILENAME2, QGROUP, QSTEP, QINDENT)
    VALUES (QNA_SEQ.NEXTVAL, 'aaa123', null, '제목', '내용', null, null, 1, 1, 1 );

-- 글 삭제하기 

UPDATE QNA SET QSTATE = 1 WHERE QNO=5;

commit;